package PKTelaLogin;

import conexao.ModuloDeConexao;
import java.text.DateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
//bibliotecas JasperReport
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Arix
 */
public class TelaPrincipal extends javax.swing.JFrame {

    Connection VarConexao = null;

    /**
     * Creates new form TelaPrincipal
     */
    public TelaPrincipal() {
        initComponents();
        VarConexao = ModuloDeConexao.conector();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jDesktop = new javax.swing.JDesktopPane();
        jLabel3 = new javax.swing.JLabel();
        lblUsuario = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblPerfil = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        MenuCadastro = new javax.swing.JMenu();
        MenuCadCliente = new javax.swing.JMenuItem();
        MenuCadOS = new javax.swing.JMenuItem();
        MenuCadUsuario = new javax.swing.JMenuItem();
        MenuRealtorio = new javax.swing.JMenu();
        jMenRelClientes = new javax.swing.JMenuItem();
        jMenRelServicos = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuEquip = new javax.swing.JMenu();
        jMenuListarEquip = new javax.swing.JMenuItem();
        MenuOpcoes = new javax.swing.JMenu();
        MenuCadSair = new javax.swing.JMenuItem();
        MenuAjuda = new javax.swing.JMenu();
        MenuCadSobre = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ARB Productions (Sistema de Ordem de Serviço)");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/PKTelaLogin/imagem/career-java.png"))); // NOI18N

        jDesktop.setPreferredSize(new java.awt.Dimension(640, 480));

        javax.swing.GroupLayout jDesktopLayout = new javax.swing.GroupLayout(jDesktop);
        jDesktop.setLayout(jDesktopLayout);
        jDesktopLayout.setHorizontalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 640, Short.MAX_VALUE)
        );
        jDesktopLayout.setVerticalGroup(
            jDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 480, Short.MAX_VALUE)
        );

        jLabel3.setText("Usuário:");

        lblUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblUsuario.setText("Usuário:");

        jLabel4.setText("Perfil do Usuário:");

        lblPerfil.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPerfil.setText("Perfil:");

        jLabel2.setText("Data do Login:");

        lblData.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblData.setText("Data:");

        MenuCadastro.setText("Cadastro");

        MenuCadCliente.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK));
        MenuCadCliente.setText("Cliente");
        MenuCadCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadClienteActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadCliente);

        MenuCadOS.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        MenuCadOS.setText("O.S");
        MenuCadOS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadOSActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadOS);

        MenuCadUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.ALT_MASK));
        MenuCadUsuario.setText("Usuários");
        MenuCadUsuario.setEnabled(false);
        MenuCadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadUsuarioActionPerformed(evt);
            }
        });
        MenuCadastro.add(MenuCadUsuario);

        Menu.add(MenuCadastro);

        MenuRealtorio.setText("Relatório");
        MenuRealtorio.setEnabled(false);

        jMenRelClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.ALT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenRelClientes.setText("Clientes");
        jMenRelClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenRelClientesActionPerformed(evt);
            }
        });
        MenuRealtorio.add(jMenRelClientes);

        jMenRelServicos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        jMenRelServicos.setText("Serviços");
        jMenRelServicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenRelServicosActionPerformed(evt);
            }
        });
        MenuRealtorio.add(jMenRelServicos);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.ALT_MASK));
        jMenuItem2.setText("O.S Relacionadas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuRealtorio.add(jMenuItem2);

        Menu.add(MenuRealtorio);

        jMenu1.setText("OS");

        jMenuItem1.setText("Emitir OS");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        Menu.add(jMenu1);

        jMenuEquip.setText("Equipamentos");

        jMenuListarEquip.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.ALT_MASK));
        jMenuListarEquip.setText("Listar Equipamentos");
        jMenuListarEquip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuListarEquipActionPerformed(evt);
            }
        });
        jMenuEquip.add(jMenuListarEquip);

        Menu.add(jMenuEquip);

        MenuOpcoes.setText("Opções");

        MenuCadSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        MenuCadSair.setText("Sair");
        MenuCadSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadSairActionPerformed(evt);
            }
        });
        MenuOpcoes.add(MenuCadSair);

        Menu.add(MenuOpcoes);

        MenuAjuda.setText("Ajuda");

        MenuCadSobre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, java.awt.event.InputEvent.ALT_MASK));
        MenuCadSobre.setText("Sobre");
        MenuCadSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuCadSobreActionPerformed(evt);
            }
        });
        MenuAjuda.add(MenuCadSobre);

        Menu.add(MenuAjuda);

        setJMenuBar(Menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblData)
                    .addComponent(jLabel2)
                    .addComponent(lblPerfil)
                    .addComponent(jLabel4)
                    .addComponent(lblUsuario)
                    .addComponent(jLabel3))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDesktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblUsuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPerfil)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(956, 562));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // Evento ocorrerá quando o form for ativado:
        // lblData e lblUsuario receberá dados automáticos do Banco de Dados
        Date DataAtual = new Date();
        DateFormat Formatador = DateFormat.getDateInstance(DateFormat.LONG);
        lblData.setText(Formatador.format(DataAtual));

    }//GEN-LAST:event_formWindowActivated

    private void MenuCadSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadSairActionPerformed
        // TODO add your handling code here:
        int sair = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja Sair?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (sair == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_MenuCadSairActionPerformed

    private void MenuCadSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadSobreActionPerformed
        // abre outro form (frmTelaSobre) 
        frmTelaSobre telaSobre = new frmTelaSobre();
        //telaSobre.show();
        telaSobre.setVisible(true);
    }//GEN-LAST:event_MenuCadSobreActionPerformed

    private void MenuCadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadUsuarioActionPerformed
        // abre o 'frmTelaUsuario' dentro do 'jDesktop' que esta na 'TelaPrincipal'
        frmTelaUsuario tUsuario = new frmTelaUsuario();
        tUsuario.setVisible(true);
        jDesktop.add(tUsuario);
    }//GEN-LAST:event_MenuCadUsuarioActionPerformed

    private void MenuCadClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadClienteActionPerformed
        // Abre a tela de cliente:
        frmCliente TCleinte = new frmCliente();
        TCleinte.setVisible(true);
        jDesktop.add(TCleinte);
    }//GEN-LAST:event_MenuCadClienteActionPerformed

    private void MenuCadOSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuCadOSActionPerformed
        // abre a tela de 'ordem de serviço':
        frmOs TelaOs = new frmOs();
        TelaOs.setVisible(true);
        jDesktop.add(TelaOs);
    }//GEN-LAST:event_MenuCadOSActionPerformed

    private void jMenRelClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenRelClientesActionPerformed
        // gerando relatorio de clientes:
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja gerar um relatório de "
                + "Clientes?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            //imprimir o relatorio com o fremework japesReport:
            try {
                // usando a classe jasperPrint p/ preparar a impressao
                JasperPrint jPrint = JasperFillManager.fillReport("C:\\Users\\Arix\\JaspersoftWorkspace\\MyReports\\clientes2.jasper", null, VarConexao);
                // exibe o relatorio atraves da classe jasperViewer
                JasperViewer.viewReport(jPrint, false);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }

        }
    }//GEN-LAST:event_jMenRelClientesActionPerformed
    
    private void jMenRelServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenRelServicosActionPerformed
        // exibe relatorio de serviço:
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja gerar um relatório de "
                + "Serviço?", "Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION) {
            //imprimir o relatorio com o fremework japesReport: 
            try {
                JasperPrint jPrint = JasperFillManager.fillReport("C:\\Users\\Arix\\JaspersoftWorkspace\\MyReports\\servicos.jasper", null, VarConexao);
                JasperViewer.viewReport(jPrint,false);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jMenRelServicosActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        frmEmissaoOs emitirOs = new frmEmissaoOs();
        emitirOs.setVisible(true);
        jDesktop.add(emitirOs);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // emite as OS que estão relacionadas com nome dos clientes:
        String relPath ="C:\\Users\\Arix\\JaspersoftWorkspace\\MyReports\\EmissaoDeOs.jasper";
        int confirma = JOptionPane.showConfirmDialog(null, "Deseja emitir o Relatório de OS "
                + "Relacionadas?","Atenção", JOptionPane.YES_NO_OPTION);
        if (confirma == JOptionPane.YES_OPTION){
            try {
                JasperPrint jPrint = JasperFillManager.fillReport(relPath, null,VarConexao);
                //JasperViewer.viewReport(jPrint,false);
                JasperViewer jv = new JasperViewer(jPrint,false);
                jv.setTitle("Relatório Cliente/OS");
                jv.setVisible(true);
            } catch (JRException ex) {
                JOptionPane.showMessageDialog(null, ex);
            }
        }
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuListarEquipActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuListarEquipActionPerformed
        // abre janela de equipamentos:
        frmListaEquip TelaListaEquip = new frmListaEquip();
        TelaListaEquip.setVisible(true);
        jDesktop.add(TelaListaEquip);
    }//GEN-LAST:event_jMenuListarEquipActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar Menu;
    private javax.swing.JMenu MenuAjuda;
    private javax.swing.JMenuItem MenuCadCliente;
    private javax.swing.JMenuItem MenuCadOS;
    private javax.swing.JMenuItem MenuCadSair;
    private javax.swing.JMenuItem MenuCadSobre;
    public static javax.swing.JMenuItem MenuCadUsuario;
    private javax.swing.JMenu MenuCadastro;
    private javax.swing.JMenu MenuOpcoes;
    public static javax.swing.JMenu MenuRealtorio;
    private javax.swing.JDesktopPane jDesktop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenuItem jMenRelClientes;
    private javax.swing.JMenuItem jMenRelServicos;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenuEquip;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuListarEquip;
    private javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblPerfil;
    public static javax.swing.JLabel lblUsuario;
    // End of variables declaration//GEN-END:variables
}
